### ISSUE TITLE
not found错误，是因为下载个数有限制吗？

### ISSUE THREAD

**Issue by meixufen** [hujiulong/dgit#6]
我使用您的工具下载了200个左右后，之后的就提示not found了，但实际repo地址是存在的，这是因为什么呢？

**Comment by hujiulong** [comment]
请提供一下具体的复现步骤

**Comment by meixufen** [comment]
我是在python项目中直接调用您的工具使用命令行进行批量下载，之前的实验中大概下载了200个便不能再下载，使用命令行单独下载也不行。
但您说让我复现一下，我再次实验时，又能下载了，但此次下载数量只有70个左右，便出现以下错误：
/allanino/sci-hub-fy

  Download complete.

  downloaded 13 files, totaling 98.81 KB.

page：19
/maximelebreton/quick-javascript-switcher
/xuender/cm
/oslego/chrome-css-shapes-editor
/Noitidart/Chrome-Store-Foxified

  Error:

  Not Found.

/vitvad/Access-Control-Allow-Origin
/niki4810/gulp-devtools
/ztratar/followr

  Error:

  Not Found.

表明/allanino/sci-hub-fy下载成功，而/Noitidart/Chrome-Store-Foxified和/ztratar/followr结果为not found。
此时我在用命令行测试：
T:\>dgit adg/github-gmail github-gmail
\   donwloading from github:adg/github-gmail/  ref: master
  Error:

  Not Found.
结果依然为找不到。
难道是因为被服务器限定了下载速率的原因？？

**Comment by meixufen** [comment]
我发现可能不是您的工具问题，而是GitHub设置了我request的速率导致的。

**Comment by hujiulong** [comment]
github的API确实有频率限制（每小时60次），但是每一次使用只消耗一次API调用，下载文件是不消耗的
